# Generated by Django 6.0.8 on 2026-08-30 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='is_honeypot',
            field=models.BooleanField(default=False, help_text='True if this hit the decoy /admin/ login rather than the real admin.'),
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('search', 'Search'), ('add_to_cart', 'Added to cart'), ('order_placed', 'Order placed')], max_length=20)),
                ('guest_id', models.CharField(blank=True, db_index=True, help_text='Stable per-browser-session id for events logged before the visitor was logged in.', max_length=40)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
