# Generated by Django 6.0.8 on 2026-08-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway_ref',
            field=models.CharField(blank=True, db_index=True, help_text='eSewa transaction_uuid or Khalti pidx for this order.', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('esewa', 'eSewa'), ('khalti', 'Khalti')], max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='processing', max_length=20),
        ),
    ]
